version: "0.2"
language: en-GB
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - abstractmethod
  - arcname
  - aread
  - ASGI
  - authlib
  - autouse
  - bitshifted
  - CHELSA
  - circlemarker
  - classmethod
  - conftest
  - dataclass
  - Dataclasses
  - dataspace
  - datatree
  - docstrings
  - dotenv
  - EPSG
  - fastapi
  - Finalizer
  - frozenset
  - GBIF
  - GRIIS
  - healthcheck
  - httpx
  - itsdangerous
  - jinja
  - letsencrypt
  - Lngs
  - Natura
  - nicegui
  - orcid
  - passlib
  - pipefail
  - Precip
  - pycache
  - Pydantic
  - pyjwt
  - pytest
  - PYTHONDONTWRITEBYTECODE
  - PYTHONUNBUFFERED
  - rocrate
  - rocratefile
  - Rscript
  - SITECODE
  - softprops
  - Starlette
  - stdlib
  - testpaths
  - urllib
  - userinfo
  - uvicorn
  - VCPUs
ignoreWords: []
import: []
